### ISSUE TITLE
fa sizes are not working in extraClasses

### ISSUE THREAD

**Issue by cordovapolymer** [coryasilva/Leaflet.ExtraMarkers#27]
Font awesome extra classes are not recognized in extraClasses, for example fa-2x gives no effect.

```
var dollar = L.ExtraMarkers.icon({
          icon: 'fa-usd',
          iconColor: 'green',
          prefix: 'fa',
          extraClasses: 'fa-2x',
          shape: 'star',
          markerColor: 'yellow'
        });
```

**Comment by coryasilva** [comment]
That was intentionally left out because I think it looks goofy to have such big icons.  Obviously a completely subjective decision.  It should not be to difficult to add a new css override for fa-2x.

**Comment by cordovapolymer** [comment]
Can you give an example of such override?

**Comment by coryasilva** [comment]
```css
.extra-marker i.fa-2x {
    font-size: 16px;
    margin-top: 9px;
}
/* or */
.extra-marker i.fa-3x {
    font-size: 18px;
    margin-top: 8px;
}
```
